### ISSUE TITLE
Firebase not working on Galaxy S7 (7.0, API 24)

### ISSUE THREAD

**Issue by rkalz** [rkalz/UABParkingFinder#25]
App refuses to download any data from Firebase as soon as iOS was implemented

**Comment by rkalz** [comment]
Works just fine in an emulator. Appears to only be happening on my phone. Could be due to deprecated functions or API issues?

Probably unrelated to iOS deployment.

**Comment by rkalz** [comment]
```
E/FirebaseApp: Firebase API initialization failure.
               java.lang.reflect.InvocationTargetException
                   at java.lang.reflect.Method.invoke(Native Method)
                   at com.google.firebase.FirebaseApp.zza(Unknown Source)
                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                   at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1758)
                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1733)
                   at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                   at android.app.ActivityThread.installProvider(ActivityThread.java:6331)
                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:5923)
                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5862)
                   at android.app.ActivityThread.-wrap3(ActivityThread.java)
                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718)
                   at android.os.Handler.dispatchMessage(Handler.java:102)
                   at android.os.Looper.loop(Looper.java:154)
                   at android.app.ActivityThread.main(ActivityThread.java:6688)
                   at java.lang.reflect.Method.invoke(Native Method)
                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                Caused by: java.lang.NoSuchMethodError: No virtual method zzEr()Ljava/lang/String; in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in /data/app/net.rofael.uabparkingfinder-2/split_lib_dependencies_apk.apk)
                   at com.google.firebase.auth.FirebaseAuth.zzb(Unknown Source)
                   at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source)
                   at java.lang.reflect.Method.invoke(Native Method) 
                   at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                   at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1758) 
                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1733) 
                   at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                   at android.app.ActivityThread.installProvider(ActivityThread.java:6331) 
                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:5923) 
                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5862) 
                   at android.app.ActivityThread.-wrap3(ActivityThread.java) 
                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718) 
                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                   at android.os.Looper.loop(Looper.java:154) 
                   at android.app.ActivityThread.main(ActivityThread.java:6688) 
                   at java.lang.reflect.Method.invoke(Native Method) 
                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
```

Well that's interesting. This version of Firebase can't find something in this version of the Android API.

**Comment by rkalz** [comment]
Got rid of that error in https://github.com/rkalz/UABParkingFinderAndroid/commit/07e28b4445bab0753a66cdb3e6efc27fa438cbbb

But still doesn't work as well as it used to. Sometimes it works, but takes a long time to even run Firebase
